### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by Neustradamus** [snikket-im/user-docs#1]
Dear @mwild1,

Several days ago, I have sent you a message and I have done a ticket which has been closed without the solution.

On https://snikket.org/ can you add the link on the logo in the footer.

Change "© 2021 Snikket Community Interest Company" by "© Copyright 2021-2022, Snikket Community Interest Company." or "© Copyright 2021-2022, Snikket Community Interest Company. All Rights Reserved."

Thanks in advance.

**Comment by mwild1** [comment]
The copyright notice is already up to date and you were asked 10 minutes ago to stop spamming the issue tracker ( https://github.com/snikket-im/snikket-web-portal/issues/116 ) (and chatrooms before that).

As far as I'm aware you are not a user of our software, and your contributions on our issue trackers are consistently low quality. We have better work to do than moderating our issue trackers, so as a result I've blocked you from filing further issues.
